--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: question; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.question (
    id integer NOT NULL,
    question_title character varying(255) NOT NULL,
    option1 character varying(255) NOT NULL,
    option2 character varying(255) NOT NULL,
    option3 character varying(255) NOT NULL,
    option4 character varying(255) NOT NULL,
    right_answer character varying(255) NOT NULL,
    difficulty_level character varying(255) NOT NULL,
    category character varying(255) NOT NULL
);


--
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.question_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.question_id_seq OWNED BY public.question.id;


--
-- Name: question_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.question_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: quiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz (
    id integer NOT NULL,
    title character varying(255)
);


--
-- Name: quiz_attempt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_attempt (
    id integer NOT NULL,
    attempted_at timestamp(6) without time zone,
    score integer,
    total_questions integer,
    quiz_id integer,
    user_id integer
);


--
-- Name: quiz_attempt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_attempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_attempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_questions (
    quiz_id integer NOT NULL,
    questions_id integer NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question ALTER COLUMN id SET DEFAULT nextval('public.question_id_seq'::regclass);


--
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.question VALUES (1, 'What is a class in Java?', 'A function', 'An object', 'A data structure', 'A loop', 'An object', 'Easy', 'java');
INSERT INTO public.question VALUES (2, 'What does OOP stand for?', 'Object-Oriented Programming', 'Object Ordering Process', 'Operating Overloaded Pointers', 'Order of Operations', 'Object-Oriented Programming', 'Easy', 'java');
INSERT INTO public.question VALUES (3, 'What is a list in Python?', 'A type of loop', 'A built-in function', 'A data structure', 'An object', 'A data structure', 'Easy', 'python');
INSERT INTO public.question VALUES (4, 'Which data structure uses First-In-First-Out (FIFO) order?', 'Stack', 'Queue', 'Array', 'LinkedList', 'Queue', 'Medium', 'python');
INSERT INTO public.question VALUES (5, 'What is a constructor?', 'A member of a class', 'A loop in Python', 'A data type', 'A special method', 'A special method', 'Medium', 'java');
INSERT INTO public.question VALUES (6, 'Which sorting algorithm has the worst-case time complexity of O(n^2)?', 'Merge Sort', 'Quick Sort', 'Insertion Sort', 'Bubble Sort', 'Bubble Sort', 'Hard', 'python');
INSERT INTO public.question VALUES (7, 'In Java, what is used to create an instance of a class?', 'Class', 'Method', 'Object', 'Constructor', 'Constructor', 'Easy', 'java');
INSERT INTO public.question VALUES (8, 'Which keyword is used to define a variable that won’t be reassigned?', 'static', 'final', 'constant', 'immutable', 'final', 'Easy', 'java');
INSERT INTO public.question VALUES (9, 'What is the output of 4 ^ 3 in Python?', '7', '64', '81', '12', '64', 'Easy', 'python');
INSERT INTO public.question VALUES (10, 'What does the term "polymorphism" refer to in programming?', 'Using multiple inheritance', 'Ability to take multiple forms', 'Manipulating data', 'Using multiple programming languages', 'Ability to take multiple forms', 'Medium', 'java');
INSERT INTO public.question VALUES (11, 'What is the purpose of the "self" parameter in Python class methods?', 'It refers to the current instance of the class', 'It is used to call parent class methods', 'It is a keyword for loops', 'It is a data type', 'It refers to the current instance of the class', 'Medium', 'python');
INSERT INTO public.question VALUES (12, 'Which of the following is not a primitive data type in Java?', 'int', 'boolean', 'char', 'string', 'string', 'Medium', 'java');
INSERT INTO public.question VALUES (13, 'What is the time complexity of a binary search?', 'O(n)', 'O(log n)', 'O(n^2)', 'O(1)', 'O(log n)', 'Medium', 'python');
INSERT INTO public.question VALUES (14, 'What keyword is used to inherit a class in Python?', 'extends', 'inherits', 'super', 'class', 'class', 'Easy', 'python');
INSERT INTO public.question VALUES (15, 'Which type of loop is ideal for situations where the number of iterations is known?', 'for loop', 'while loop', 'do-while loop', 'until loop', 'for loop', 'Easy', 'java');
INSERT INTO public.question VALUES (16, 'What is the purpose of "import" in Python?', 'To export data', 'To create a backup', 'To include external modules', 'To print output', 'To include external modules', 'Easy', 'python');
INSERT INTO public.question VALUES (17, 'In Java, which access modifier provides the widest visibility?', 'public', 'private', 'protected', 'package-private', 'public', 'Easy', 'java');
INSERT INTO public.question VALUES (18, 'What is a lambda function in Python?', 'A function that uses the "lambda" keyword', 'A function with multiple return values', 'A function with no parameters', 'An anonymous inline function', 'An anonymous inline function', 'Medium', 'python');
INSERT INTO public.question VALUES (19, 'What is a linked list?', 'A type of array', 'A linear data structure', 'A collection of objects', 'A group of classes', 'A linear data structure', 'Medium', 'java');
INSERT INTO public.question VALUES (20, 'Which operator is used to concatenate strings in Python?', '&', '+', '*', '++', '+', 'Easy', 'python');
INSERT INTO public.question VALUES (21, 'What does JVM stand for?', 'Java Virtual Machine', 'Just Virtual Memory', 'JavaScript Virtual Machine', 'Java Version Manager', 'Java Virtual Machine', 'Easy', 'java');
INSERT INTO public.question VALUES (22, 'In Python, what is the main difference between a tuple and a list?', 'Tuples are mutable, lists are not', 'Lists are ordered, tuples are not', 'Tuples can store mixed data types, lists cannot', 'Lists have a fixed size, tuples do not', 'Tuples can store mixed data types, lists cannot', 'Medium', 'python');
INSERT INTO public.question VALUES (23, 'What is the purpose of the "finally" block in a try-catch-finally statement?', 'To handle exceptions', 'To define a fallback value', 'To execute code regardless of exceptions', 'To terminate the program', 'To execute code regardless of exceptions', 'Medium', 'java');
INSERT INTO public.question VALUES (24, 'What is a dictionary in Python?', 'A sorted collection of elements', 'A data structure used for searching', 'An ordered sequence of elements', 'A key-value store', 'A key-value store', 'Easy', 'python');
INSERT INTO public.question VALUES (25, 'Which keyword is used to define a subclass in Java?', 'child', 'extends', 'inherits', 'subclass', 'extends', 'Easy', 'java');
INSERT INTO public.question VALUES (26, 'What is the purpose of the "pass" statement in Python?', 'To stop the execution of a loop', 'To indicate an empty code block', 'To raise an exception', 'To terminate the program', 'To indicate an empty code block', 'Easy', 'python');
INSERT INTO public.question VALUES (27, 'What is maximum value for byte in Java?', '127', '100', '255', '999', '127', 'Easy', 'java');
INSERT INTO public.question VALUES (28, 'What is maximum value for byte in Java?', '127', '100', '255', '999', '127', 'Easy', 'java');


--
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.quiz VALUES (1, 'Java Basics');
INSERT INTO public.quiz VALUES (2, 'Object Oriented Programming');
INSERT INTO public.quiz VALUES (3, 'Java Collections');
INSERT INTO public.quiz VALUES (4, 'Python Basics');
INSERT INTO public.quiz VALUES (5, 'Python Programming');
INSERT INTO public.quiz VALUES (6, 'Python Advanced');


--
-- Data for Name: quiz_attempt; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.quiz_attempt VALUES (17, '2026-07-05 17:02:54.848579', 4, 5, 1, 3);
INSERT INTO public.quiz_attempt VALUES (18, '2026-07-05 17:15:16.751371', 3, 5, 1, 3);


--
-- Data for Name: quiz_questions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.quiz_questions VALUES (1, 2);
INSERT INTO public.quiz_questions VALUES (1, 15);
INSERT INTO public.quiz_questions VALUES (1, 27);
INSERT INTO public.quiz_questions VALUES (1, 12);
INSERT INTO public.quiz_questions VALUES (1, 23);
INSERT INTO public.quiz_questions VALUES (2, 2);
INSERT INTO public.quiz_questions VALUES (2, 23);
INSERT INTO public.quiz_questions VALUES (2, 5);
INSERT INTO public.quiz_questions VALUES (2, 12);
INSERT INTO public.quiz_questions VALUES (2, 27);
INSERT INTO public.quiz_questions VALUES (3, 8);
INSERT INTO public.quiz_questions VALUES (3, 23);
INSERT INTO public.quiz_questions VALUES (3, 7);
INSERT INTO public.quiz_questions VALUES (3, 28);
INSERT INTO public.quiz_questions VALUES (3, 25);
INSERT INTO public.quiz_questions VALUES (4, 6);
INSERT INTO public.quiz_questions VALUES (4, 14);
INSERT INTO public.quiz_questions VALUES (4, 11);
INSERT INTO public.quiz_questions VALUES (4, 4);
INSERT INTO public.quiz_questions VALUES (4, 16);
INSERT INTO public.quiz_questions VALUES (5, 18);
INSERT INTO public.quiz_questions VALUES (5, 26);
INSERT INTO public.quiz_questions VALUES (5, 22);
INSERT INTO public.quiz_questions VALUES (5, 11);
INSERT INTO public.quiz_questions VALUES (5, 13);
INSERT INTO public.quiz_questions VALUES (6, 26);
INSERT INTO public.quiz_questions VALUES (6, 4);
INSERT INTO public.quiz_questions VALUES (6, 24);
INSERT INTO public.quiz_questions VALUES (6, 11);
INSERT INTO public.quiz_questions VALUES (6, 16);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users VALUES (1, 'vishvam@gmail.com', 'Vishvam', '12345');
INSERT INTO public.users VALUES (2, 'rahul@gmail.com', 'Rahul', '$2a$10$E6h0h0HlFtEFh.F.jn333.Ha8n9.KJBvHWr9J5bUM.oVGRrDrGMni');
INSERT INTO public.users VALUES (3, 'abc@gmail.com', 'abc', '$2a$10$2NcAUckdzIT9lB8NS07PkuoEhmapnOcR3J3RfEycEduMNwAtfKDLS');


--
-- Name: question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.question_id_seq', 28, true);


--
-- Name: question_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.question_seq', 1, true);


--
-- Name: quiz_attempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_attempt_id_seq', 18, true);


--
-- Name: quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_id_seq', 6, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- Name: quiz_attempt quiz_attempt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt
    ADD CONSTRAINT quiz_attempt_pkey PRIMARY KEY (id);


--
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: quiz_attempt fk8l6wmgul0rgeha0lp6abrp5fa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt
    ADD CONSTRAINT fk8l6wmgul0rgeha0lp6abrp5fa FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


--
-- Name: quiz_questions fkcgp9e1c6ww3t383aui4w8feae; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkcgp9e1c6ww3t383aui4w8feae FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


--
-- Name: quiz_attempt fkdwtjplymtc83ovymfhx0fk2a5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempt
    ADD CONSTRAINT fkdwtjplymtc83ovymfhx0fk2a5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: quiz_questions fkpmfvwer12y1nrjc0efm04dq16; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkpmfvwer12y1nrjc0efm04dq16 FOREIGN KEY (questions_id) REFERENCES public.question(id);


--
-- PostgreSQL database dump complete
--

